version: "3.8"
services:
  database:
    image: mongo:4.4-bionic
    container_name: "management_tool_mongodb"
    env_file:
        - .env
    ports:
        - 27017:27017
    environment:
        - "MONGO_INITDB_DATABASE=${MONGO_DATABASE}"
        - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}"
        - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}"
    volumes:
        - ./mongo-volume:/data/db
